### ISSUE TITLE
requirements for imdb dataset

### ISSUE THREAD

**Issue by mrbeann** [pliang279/MultiBench#9]
It seems the imdb dataset uses the theano and blocks, what is the system and version requirement for these? I have tried the official link, but it seems not working.
https://blocks.readthedocs.io/en/latest/setup.html

Some error message like,
```
File "/tmp/pip-install-sazv5l9d/toolz_ccc093e7dfa34bf2af1fb5c703132aa3/toolz/functoolz.py", line 467
      f.__name__ for f in reversed((self.first,) + self.funcs),
      ^
  SyntaxError: Generator expression must be parenthesized

```

**Comment by mrbeann** [comment]
BTW, I also found that humor and sarcasm not work properly. 
e.g., for  sarcasm
```
    alldata['train'] = drop_entry(alldata['train'])
KeyError: 'train'
```

**Comment by Vanvan2017** [comment]
So sorry for the error in sarcasm and humor, this is may due to the dictionary of the processed data not updated to the unique data_loader for all when refactoring the code, please check this version: https://drive.google.com/drive/folders/1NTtr27Of3h7ou03Qvt51wYgf9hTMJ4YL?usp=sharing, this should be works fine~

**Comment by Vanvan2017** [comment]
> BTW, I also found that humor and sarcasm not work properly. e.g., for sarcasm
> 
> ```
>     alldata['train'] = drop_entry(alldata['train'])
> KeyError: 'train'
> ```

We also have updated data and new features of data loaders in README~

**Comment by mrbeann** [comment]
Thank you for your reply, what about the IMDB dataset?

**Comment by neal-ztwu** [comment]
> Thank you for your reply, what about the IMDB dataset?

Sorry for the late reply. 
I am not sure why your situation happened but I have pushed an environment file in the repo. Could you please try again using the same environment with our work? Thanks!

**Comment by mrbeann** [comment]
> > Thank you for your reply, what about the IMDB dataset?
> 
> Sorry for the late reply. I am not sure why your situation happened but I have pushed an environment file in the repo. Could you please try again using the same environment with our work? Thanks!

Thank you for your reply. It still does not work. It reported the "block" is missing.

BTW, recent updates seem to make this repo unable to run. @Vanvan2017 @neal-ztwu

**Comment by abhinavnippani** [comment]
Is there any way to access the VGGNet model and data used to extract parameters/features in vgg.py and get_data.py ?

The repo for this (multibench) seems to have been deleted.

TIA
